### ISSUE TITLE
Paths might be different

### ISSUE THREAD

**Issue by riconeitzel** [brandonjjon/tp-importer#1]
Hey everyone!

I case you come across the issue that it gave no error on the CLI but didn't work in Table Plus either … or that it tells you a folder could not be found: I'm using TablePlus via SetApp Subscription and my TablePlus folders in Application Support have a different folder name. 

You can either run the script without changing it and copy the files afterwards (if no error) or
You can alter the paths in the script to make it work with your setup :-)

Remember: Passwords are gone but you can still copy them from keychain access and paste them in the connection setting's screen of table plus!

HTH
Rico

**Comment by brandonjjon** [comment]
Hi Rico,

Good catch. I was thinking the whole time I was developing that there might be a case where the paths would be different. One way we could handle would be to add path flags when running via the cli to be able to set custom paths.

Let me know if that's something you would want to take a stab at! Also might be worth thinking about the whole cross-compatible issue as a whole since this was only designed to be run on macOS at the moment.

Thanks

**Comment by Schrank** [comment]
If one changes the paths in `src/importer.js` it works like a charm <3

**Comment by Schrank** [comment]
Need to correct myself, it seems the passwords are not brought over...

**Comment by brandonjjon** [comment]
@Schrank That's correct I made a note in the readme that this script does not bring over passwords. If you're on MacOS though you can typically grab the passwords from your Keychain.

Hopefully that helps.

**Comment by Schrank** [comment]
Some people ↖️  are too dumb to read Readmes. Thanks for trying <3
